datasource:
  driver-class-name: "org.postgresql.Driver"
  url: "jdbc:postgresql://postgresql:5430"
  username: "local"
  password: "local"


volume-path:
  persistent-volume-data: "/Users/labtop/intellij/kubernetes-anotherclass-api-tester/volume/local/pv/"
  pod-volume-data: "/Users/labtop/intellij/kubernetes-anotherclass-api-tester/volume/local/pod/"
